# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto
# Protobuf Python Version: 4.25.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\"\x1f\n\x0b\x43lientHello\x12\x10\n\x08nickname\x18\x01 \x01(\t\"\x1c\n\rClientSendMsg\x12\x0b\n\x03msg\x18\x01 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CLIENTHELLO']._serialized_start=14
  _globals['_CLIENTHELLO']._serialized_end=45
  _globals['_CLIENTSENDMSG']._serialized_start=47
  _globals['_CLIENTSENDMSG']._serialized_end=75
# @@protoc_insertion_point(module_scope)
